---
DESIGN_NAME: async_fifo
VERILOG_FILES: dir::rtl/*.sv
CLOCK_PERIOD: 7
CLOCK_PORT:
  - wr_clk_i
  - rd_clk_i
# Power Distribution Garbage
FP_PDN_VOFFSET: 7
FP_PDN_HOFFSET: 7
FP_PDN_SKIPTRIM: true
RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GRT_DESIGN_REPAIR: true
# Debug
SYNTH_AUTONAME: true
# SDC file
PNR_SDC_FILE: constraints.sdc
SIGNOFF_SDC_FILE: constraints.sdc
